app:
  app_name: ScoutService
  debug: false
  host: localhost
  port: 5004
  logging:
      logger_name: ScoutServiceLogger
      app_name: ScoutService
      level: info
      file: scout_service.log
      file_level: info
  recent_viewed_limit: 20

database:
  connector: postgres
  dbname: qrook_scout
  username: kurush
  password: pondoxo
  host: localhost
  port: 5432
  logging:
    logger_name: DatabaseLogger
    app_name: ScoutService
    level: info
    file: scout_service.log
    file_level: info

jwt:
  jwks_uri: http://localhost:5001/oauth/.well-known/jwks
  iss: https://authlib.org  # todo
  aud: pRiDvVWqbMdVcqUcubD0Y54V # audience (client_id)

kafka_consumer:
  config:
    bootstrap.servers: localhost:29092
    group.id: qrook_scout
    auto.offset.reset: earliest        # latest
    enable.auto.commit: true
  topics: using_filters searching view_author view_series view_book download_book