app:
  app_name: FileService
  debug: false
  host: localhost
  port: 5003
  logging:
      logger_name: FileServiceLogger
      app_name: FileService
      level: info
      file: file_service.log
      file_level: info

file_storage:
  books: books/

jwt:
  jwks_uri: http://localhost:5001/oauth/.well-known/jwks
  iss: https://authlib.org  # todo
  aud: pRiDvVWqbMdVcqUcubD0Y54V # audience (client_id)

kafka_producer:
  bootstrap.servers: localhost:29092