apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-service
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: kafka-port1
      protocol: TCP
      port: 29092
      targetPort: 29092
    - name: kafka-port2
      protocol: TCP
      port: 9092
      targetPort: 9092