app:
  app_name: GatewayService
  debug: false
  host: 0.0.0.0
  port: 5001

database:
  connector: postgresql
  dbname: qrook_auth
  username: kurush
  password: pondoxo
  host: qrook-postgres-service
  port: 5432

jwt:
  kid: unexpectedly_an_id
  private_key: ./auth/etc/jwtRS256.key
  public_key: ./auth/etc/jwtRS256.key.pub
  alg: RS256
  iss: http://kurush7.cloud.okteto.net
  exp: 86400                # seconds

  aud: pRiDvVWqbMdVcqUcubD0Y54V # audience (client_id)

dummy_client:
  id: '12345'
  secret: '12345'
  iss: http://kurush7.cloud.okteto.net  # issuer from admin!